// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhrlgqfpfvogxkyjfhfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ocmxncWZwZnZvZ3hreWpmaGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQ3MDUsImV4cCI6MjA2NTQ3MDcwNX0.aiipg0nqZotV1A8GtKt7988BI3p93TB6LcREzXxoKj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);