// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txxaylhspzsqpjbqqlxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4eGF5bGhzcHpzcXBqYnFxbHhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDc1NDIsImV4cCI6MjA2NDAyMzU0Mn0.Czb8iDWLB3quTdIvRQk2kthUWklbDG312dOga-8c9Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);